globalPolicies:
  inbound:
    # Auth0 JWT Auth (For testing)
    - jwt_auth:
        jwk_url: "https://dev-dej0y58ibefglict.us.auth0.com/.well-known/jwks.json"
        audience: "test-api"
        issuer: "https://dev-dej0y58ibefglict.us.auth0.com/"
        algorithms: ["RS256"]
    - rate_limit:
        requests_per_minute: 50
        requests_per_minute_per_user_per_ip: 10
  backend: []
    #- set_header:
    #    key: "X-Custom-Header"
  outbound: []
  onError:
    - retry:
        max_attempts: 3
        backoff_seconds: 1.0
    #- custom_error_response:
    #    error_code: "GLOBAL_FAILURE"
    #    status_code: 500

